language: node_js
node_js:
    - lts/*
cache: yarn
notifications:
    email: false
script: yarn verify
env:
    global:
        - secure: J4lXntN7sGnhRRXbni2HnWduAQXfdv/BuJLO+EWJf9UA2c9zL+2sqRu9n04H6YFAgku+XzeKPMv0bMnaCTG0nAMD+w1vc4SG87sdk5MpeS5+QMbdgaEe51W2PRAGVXLTJ2QLnToqudqwr65YuOYux8W5ZO0T8Qp7mnXh5POWylUio2jUkIwCr3tQJjrW1H6dT7IM2qDuvOCrOvZX/t3O8FkESqdCQPTLrB6rZMMKPCBF5s4VB81gIO9sb4R+ISS4gPI4LvXR3mVHXlOPfYGyhUyvh5XCMSjaWNEXUojjLf3q9CUk+VVcj0SGjGYqVB1YsCcqphZWXpbkjeURKbqPol6/zCAsBpndbgfycxcNkDlow08avQMPqCAKGu8hAwSDmMv+c7CoYMVhnFjXAZtzukPC4YGkQ4Fjr/GgHGshnaxLD9jPRlaFSB3jxvs0PibK2OniPGDeVxsfS5tvKKM2Kw+rr2z7zpApe3Kd7hOi1v0tz1MBYFBbTXvjuwbjUEdb57qIj15fQbvxQseZPM9sUeAiMg80CKuikMXFE1b2R5AoEenl+Kdwb4UhDvQRKOaKRo78o13myuhSjNPtzliZBpyosO7pKWvCn/hu8kO9QVEWYb5b8BwmEfFTDUvcopO54hoxyDqUP/kQDUiSU9vTzz7t/+9vOrrqp8hl8kUAw/Y=
        - secure: meuL51PsIZK7CICDeGS5Wqdnx8mM6nVVzluI9/Mw7/KeGcovusNSRw+VQfXjdq1gnwk+JkpKViHzWgj9SdA4RYOsTtyqIBV7AHAnjmGoRAnuMrtZBI9B5sxgXM2iUt+3/VrjZ5rK1jurjgdGcPBzfDcT1invesQGn6g9//4E2fKPUsZf9ize6Le92IaFn5sU2ddsUeXTKB9UhL939pikoSVJlkSDWoSVhgGDA7sQDE9r27gQQFct+LicHeNu+N921h0yR86ONn9p9oW/WHNRsWWLF6Qky64Nrh/ahHXL27LxeW4UGD/WKgDS69h3funn/u4UY4oFhr0qG14EFs2IWpnZ0nyAswjqUmzkujT6p2IavimZ4SdknbJDiuy6sjxO695GvLMtTSg2W22TgAcR6FReF4h1YW8DvJzGl20rfPKHs/uGSARwFj4FY6EdlYL29c3t8+T7ItQC8hceEE8WRPhg6AvtbO+73Gt62FIFgmpInVF9RI4FoHymcuQOWAxHfBDNBgY2MrGAXpIy3NE/JzBtHlBgstFUYJsJTq45k3kc0NY4+t6jasz31Xe6BCWx2MBwThCYs7ztu0i+NxV6zYp19txAu+Czbrl6rv76s5pm4jrbaqY59wukOEZrRQSVhh39q8JIO4aP2SjQ+BeV6pzrxMxASNANBnRqdlU+1wc=

jobs:
    include:
        # Define the release stage that runs semantic-release
        - stage: release
          node_js: lts/*
          script: skip
          deploy:
              provider: script
              skip_cleanup: true
              script:
                  - npx semantic-release
