language: node_js
node_js:
- lts/*
cache: yarn
notifications:
  email: false
script: yarn verify
jobs:
  include:
  - stage: release
    node_js: lts/*
    script: skip
    deploy:
      provider: script
      skip_cleanup: true
      script:
      - npx semantic-release
env:
  global:
  - secure: paNfcAsY3HmwY3Wamy6XCcb5215g7m7HyIlQtl8UGgAm7GNM/dU/qvHk3lvpqHlGY/eJ5Q9+/0WRvTTQeFDhlj2I9jshPULGzfPhF2GXEcMa05rJie479XyUvcOGf3PDUqQ2Mhg6gDtphavt9SJ2wMYBktzOLQFA4tnSJ/OMKmOyux4kT97+7QhZ6bgChNZ4GQcfwHNVxT8IHCelnqoaL0p/MqHA0rdHFl3pTkCO8ZpVJ32GmDKmSuSfoHdbHJUDNhzICyOjZuAgLn3AtzYvRo/so7YOKYcBcmgtcWWoCeJJc2qE9S/IpI3CizavSLRkxY4r9e2RtmepOmL/2u/vYEw+jyqze8GUvyu5imeYeUtswuYFuszoL9seLOPzm7Q44L9uD7pHv60ffeFb0afu3e9Sb1pybOoqJw39PQgvmxjRurz1dnSKeKyabDCIGlmVhUPpdpV5YghDkHHUMqrHlG9UHmYTfqqWqtGIwe9o7dhnqqxmRgrr7eYvuEf29Q9dSqOgSshnfPZFbtqV3gfE2hotzjcCcChkxZD0OuiJr1XSM12K724jpNsOY/awPPtLUodgpVwO39/RkO6jmgOENHtziOdvfxKzonxb8Jh++LhGeB/jlsEe0omaIlcsZuIQcfj/KbcYJLbLtG0sXZqkin60li5pqA3/5hJXt+eSePY=
  - secure: FUTxO0kNHEKuoKlv/WLpC9wzJmaI8DqVVIOdFZ3+xSECHcXHDkiBLki+q/CJaipBQ1CM+fjLzP95G6/8FxlS9lVJTaomaTD8yu8/SFz/rEwxPXE7hcqug/dbK8oyQd9gHXebuHoUGxAMMNWIjSThNZPUtpaE9is/oS3/3tzHAgFEKmDc4VHeIwwG8TNnJO0qChIkqZ8YK9D85Tr5uniIDwn2EFqOrOzIi6zcJj4G4+h+kuLaP9RtujlB6AOHjkfJuWUKtzLNX4wh4+tKVV26oBSHEiWidtQH5v9bqFa0ycp4G3tiFqjee1jjnQWoN16sd84i4g0TcPG4/niGVPBv2w3SE9d5agyQCVF/KoVE518vDUl9ES/u6WQ9p0EaGMluPt+PJQD+aZtCXrKy4mT37fJci2SVybrM3mnMMxb+eNasGiZQ3druYjhomjlCWTGuWKeMSYUh6Byppe0tvrEP705rW1Q2+sUFGVPuyWUFDlpim5024oAAOUsKobSwKSbbrHrqj4MEM5R9AXtlM9Q4iJ40xGxy7r1DbgIi5L6BVmEx48fZpM5CbBtZ00UOVrbFsFHiDbjnZJnTMWMgeMHaeYwPS9BNQLeQ6cbjQKjxILhWwu1RXvlRM2kg6fENvd36buvHrBKhO4hL3rKsxdYwkovkfzEuR/6bJfQsjQEhr9E=
